### ISSUE TITLE
Stack 직접 구현 ?

### ISSUE THREAD

**Issue by prk4224** [bc-back-end-study/book-CS#8]
### Stack 직접 구현 해야되는 이유
: 자료 구조를 정리하면서 Stack 은 직접구현해서 사용하는 것이 좋다 라는 글들을 많이 봤는데, 찾아보니 Stack 이 SOILD 5원칙 중 리스코프 치환원칙을 위배된 대표적은 사례로 뽑히고 그래서 직접 구현하는 게 좋다고 생각했습니다.

### 리스코프 치환 원칙
: 상위 타입의 객체를 하위 타입의 객체로 치환해도 상위 타입을 사용하는 프로그램은 정상적으로 동작해야 한다.

### 위배된 이유
: 기능적으로는 위배되지 않지만, 원칙적으로는 Stack 은 Index로 접근할 수 없는데 Vector를 상속 받아서 Index 접근이 가능해 애초에 상속을 잘못 받은 사례로도 뽑힌다고 합니다.

### ❓

- 이외에도 다양한 이유로 Stack 을  직접 구현해야한다고 하는데, 혹시 아시는 분 있으시면 답변 부탁 드리겠습니다.

-  제가 생각하기에 Vector 를 변경하지 않는 이유는 다른 클래스들과에 호환 때문에 변경하지 않고 있다고 생각하는데, 다른 분들의 의견이 궁금합니다.
- 제가 이해한 내용에서 잘못된 점 있으면 말씀 부탁 드리겠습니다.

**Comment by pjtae0328** [comment]
저는 개인적으로 solid는 약간 약팔이 느낌이 있다고 생각하지만 위 의견에는 공감합니다. Stack이 vector를 상속하도록 구현한건 올바른 디자인이 아니라고 생각합니다. 스택을 그 목적에 맞게 사용하는데 인덱스를 통한 접근은 필요 없어서 접근을 허용하도록 해놓은 부분은 실수로 인한 오작동을 유발할 수 있다고 생각합니다. Stack을 인터페이스로 만들고 벡터가 구현하던가 stack에서 벡터를 컴포지션 관계로 소유한 상태로 구현했어야 했다고 봅니다.

**Comment by pjtae0328** [comment]
또 일반적으로 스택이 필요한 부분에서 vector처럼 동적 배열이 필요한 경우는 거이 없기 때문에 배열로 크기를 한정하고 직접 구현하는 경우가 많습니다. 이는 알고리즘 문제를 풀때처럼 객체가 아닌 프리미티브 타입 변수를 스택에 넣어야 할때도 많은데 백터나 어레이리스트 처럼 제네릭을 활용해 Object 배열을 구현하는 객체를 활용한다면 힙영역을 한번더 참조해야하는것과 더불어 프리미티브 타입 변수를 구지 박싱하여 임뮤터블한 객체로서 활용해야 하기에 박싱과 언박싱에서 발생하는 오버헤드도 감수해야 합니다.(정수형의 경우 -128~127 의 캐시풀 영역은 제외) 만들기 어려운 것도 아니어서 만드는게 좋을 수 있겠죠 그래도 취업용 알고리즘 문제를 풀때는 풀이시간을 아끼고 구현중 실수로 인한 버그 발생 확률을 낮추기위해 이미 구현된 스택 활용을 추천합니다.

**Comment by pjtae0328** [comment]
혹시 스택을 직접 구현해야 한다는 주장이 담긴 글들 알려주실 수 있나요? 딱히 작은 성능까지 고려해야 하는 경우나 실수로 벡터처럼 사용할 여지가 있는경우가 아니라면 딱히 직접 구현해야할 큰 이유가 있을것 같지는 않아서요

**Comment by prk4224** [comment]
> 혹시 스택을 직접 구현해야 한다는 주장이 담긴 글들 알려주실 수 있나요? 딱히 작은 성능까지 고려해야 하는 경우나 실수로 벡터처럼 사용할 여지가 있는경우가 아니라면 딱히 직접 구현해야할 큰 이유가 있을것 같지는 않아서요

저도 따로 저장해두진 않았는데 그런 글들이 많이 보여서요. 한번 찾아보고 공유해 드릴게요 !
